// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: computeruse/v1/computeruse.proto

package computerusev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MouseButton int32

const (
	MouseButton_MOUSE_BUTTON_UNSPECIFIED MouseButton = 0
	MouseButton_MOUSE_BUTTON_LEFT        MouseButton = 1
	MouseButton_MOUSE_BUTTON_RIGHT       MouseButton = 2
	MouseButton_MOUSE_BUTTON_MIDDLE      MouseButton = 3
)

// Enum value maps for MouseButton.
var (
	MouseButton_name = map[int32]string{
		0: "MOUSE_BUTTON_UNSPECIFIED",
		1: "MOUSE_BUTTON_LEFT",
		2: "MOUSE_BUTTON_RIGHT",
		3: "MOUSE_BUTTON_MIDDLE",
	}
	MouseButton_value = map[string]int32{
		"MOUSE_BUTTON_UNSPECIFIED": 0,
		"MOUSE_BUTTON_LEFT":        1,
		"MOUSE_BUTTON_RIGHT":       2,
		"MOUSE_BUTTON_MIDDLE":      3,
	}
)

func (x MouseButton) Enum() *MouseButton {
	p := new(MouseButton)
	*p = x
	return p
}

func (x MouseButton) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MouseButton) Descriptor() protoreflect.EnumDescriptor {
	return file_computeruse_v1_computeruse_proto_enumTypes[0].Descriptor()
}

func (MouseButton) Type() protoreflect.EnumType {
	return &file_computeruse_v1_computeruse_proto_enumTypes[0]
}

func (x MouseButton) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MouseButton.Descriptor instead.
func (MouseButton) EnumDescriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{0}
}

type ScrollDirection int32

const (
	ScrollDirection_SCROLL_DIRECTION_UNSPECIFIED ScrollDirection = 0
	ScrollDirection_SCROLL_DIRECTION_UP          ScrollDirection = 1
	ScrollDirection_SCROLL_DIRECTION_DOWN        ScrollDirection = 2
	ScrollDirection_SCROLL_DIRECTION_LEFT        ScrollDirection = 3
	ScrollDirection_SCROLL_DIRECTION_RIGHT       ScrollDirection = 4
)

// Enum value maps for ScrollDirection.
var (
	ScrollDirection_name = map[int32]string{
		0: "SCROLL_DIRECTION_UNSPECIFIED",
		1: "SCROLL_DIRECTION_UP",
		2: "SCROLL_DIRECTION_DOWN",
		3: "SCROLL_DIRECTION_LEFT",
		4: "SCROLL_DIRECTION_RIGHT",
	}
	ScrollDirection_value = map[string]int32{
		"SCROLL_DIRECTION_UNSPECIFIED": 0,
		"SCROLL_DIRECTION_UP":          1,
		"SCROLL_DIRECTION_DOWN":        2,
		"SCROLL_DIRECTION_LEFT":        3,
		"SCROLL_DIRECTION_RIGHT":       4,
	}
)

func (x ScrollDirection) Enum() *ScrollDirection {
	p := new(ScrollDirection)
	*p = x
	return p
}

func (x ScrollDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScrollDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_computeruse_v1_computeruse_proto_enumTypes[1].Descriptor()
}

func (ScrollDirection) Type() protoreflect.EnumType {
	return &file_computeruse_v1_computeruse_proto_enumTypes[1]
}

func (x ScrollDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScrollDirection.Descriptor instead.
func (ScrollDirection) EnumDescriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{1}
}

type ListAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsRequest) Reset() {
	*x = ListAppsRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsRequest) ProtoMessage() {}

func (x *ListAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsRequest.ProtoReflect.Descriptor instead.
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{0}
}

type ListAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*AppInfo             `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{1}
}

func (x *ListAppsResponse) GetApps() []*AppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

type AppInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BundleId  string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	IsRunning bool                   `protobuf:"varint,3,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	// Days since last used (0 = currently running).
	DaysSinceUsed int32 `protobuf:"varint,4,opt,name=days_since_used,json=daysSinceUsed,proto3" json:"days_since_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{2}
}

func (x *AppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppInfo) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *AppInfo) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *AppInfo) GetDaysSinceUsed() int32 {
	if x != nil {
		return x.DaysSinceUsed
	}
	return 0
}

type GetAppStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// App name or bundle identifier.
	App           string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppStateRequest) Reset() {
	*x = GetAppStateRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppStateRequest) ProtoMessage() {}

func (x *GetAppStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppStateRequest.ProtoReflect.Descriptor instead.
func (*GetAppStateRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppStateRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type GetAppStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rendered accessibility tree as human-readable text.
	// Each element has an index used for subsequent action calls.
	AccessibilityTree string `protobuf:"bytes,1,opt,name=accessibility_tree,json=accessibilityTree,proto3" json:"accessibility_tree,omitempty"`
	// Screenshot of the app's key window as PNG bytes (Retina resolution).
	ScreenshotPng []byte   `protobuf:"bytes,2,opt,name=screenshot_png,json=screenshotPng,proto3" json:"screenshot_png,omitempty"`
	AppInfo       *AppInfo `protobuf:"bytes,3,opt,name=app_info,json=appInfo,proto3" json:"app_info,omitempty"`
	// Window bounds in screen coordinates (logical points).
	WindowBounds  *Rect `protobuf:"bytes,4,opt,name=window_bounds,json=windowBounds,proto3" json:"window_bounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppStateResponse) Reset() {
	*x = GetAppStateResponse{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppStateResponse) ProtoMessage() {}

func (x *GetAppStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppStateResponse.ProtoReflect.Descriptor instead.
func (*GetAppStateResponse) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppStateResponse) GetAccessibilityTree() string {
	if x != nil {
		return x.AccessibilityTree
	}
	return ""
}

func (x *GetAppStateResponse) GetScreenshotPng() []byte {
	if x != nil {
		return x.ScreenshotPng
	}
	return nil
}

func (x *GetAppStateResponse) GetAppInfo() *AppInfo {
	if x != nil {
		return x.AppInfo
	}
	return nil
}

func (x *GetAppStateResponse) GetWindowBounds() *Rect {
	if x != nil {
		return x.WindowBounds
	}
	return nil
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         float64                `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{5}
}

func (x *Rect) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rect) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rect) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rect) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ClickRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// Element index from accessibility tree (mutually exclusive with x/y).
	ElementIndex string `protobuf:"bytes,2,opt,name=element_index,json=elementIndex,proto3" json:"element_index,omitempty"`
	// Screenshot pixel coordinates (mutually exclusive with element_index).
	X float64 `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	// Number of clicks. Defaults to 1.
	ClickCount    int32       `protobuf:"varint,5,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	MouseButton   MouseButton `protobuf:"varint,6,opt,name=mouse_button,json=mouseButton,proto3,enum=computeruse.v1.MouseButton" json:"mouse_button,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickRequest) Reset() {
	*x = ClickRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickRequest) ProtoMessage() {}

func (x *ClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickRequest.ProtoReflect.Descriptor instead.
func (*ClickRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{6}
}

func (x *ClickRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ClickRequest) GetElementIndex() string {
	if x != nil {
		return x.ElementIndex
	}
	return ""
}

func (x *ClickRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClickRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClickRequest) GetClickCount() int32 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *ClickRequest) GetMouseButton() MouseButton {
	if x != nil {
		return x.MouseButton
	}
	return MouseButton_MOUSE_BUTTON_UNSPECIFIED
}

type TypeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeTextRequest) Reset() {
	*x = TypeTextRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeTextRequest) ProtoMessage() {}

func (x *TypeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeTextRequest.ProtoReflect.Descriptor instead.
func (*TypeTextRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{7}
}

func (x *TypeTextRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *TypeTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PressKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// Key or key combination in xdotool syntax.
	// Examples: "Return", "Tab", "super+c", "F1", "BackSpace", "KP_0"
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressKeyRequest) Reset() {
	*x = PressKeyRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressKeyRequest) ProtoMessage() {}

func (x *PressKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressKeyRequest.ProtoReflect.Descriptor instead.
func (*PressKeyRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{8}
}

func (x *PressKeyRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *PressKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ScrollRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	App          string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	ElementIndex string                 `protobuf:"bytes,2,opt,name=element_index,json=elementIndex,proto3" json:"element_index,omitempty"`
	Direction    ScrollDirection        `protobuf:"varint,3,opt,name=direction,proto3,enum=computeruse.v1.ScrollDirection" json:"direction,omitempty"`
	// Number of pages to scroll. Fractional values supported. Defaults to 1.
	Pages         float64 `protobuf:"fixed64,4,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrollRequest) Reset() {
	*x = ScrollRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollRequest) ProtoMessage() {}

func (x *ScrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollRequest.ProtoReflect.Descriptor instead.
func (*ScrollRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{9}
}

func (x *ScrollRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ScrollRequest) GetElementIndex() string {
	if x != nil {
		return x.ElementIndex
	}
	return ""
}

func (x *ScrollRequest) GetDirection() ScrollDirection {
	if x != nil {
		return x.Direction
	}
	return ScrollDirection_SCROLL_DIRECTION_UNSPECIFIED
}

func (x *ScrollRequest) GetPages() float64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type DragRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	FromX         float64                `protobuf:"fixed64,2,opt,name=from_x,json=fromX,proto3" json:"from_x,omitempty"`
	FromY         float64                `protobuf:"fixed64,3,opt,name=from_y,json=fromY,proto3" json:"from_y,omitempty"`
	ToX           float64                `protobuf:"fixed64,4,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY           float64                `protobuf:"fixed64,5,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DragRequest) Reset() {
	*x = DragRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DragRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragRequest) ProtoMessage() {}

func (x *DragRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragRequest.ProtoReflect.Descriptor instead.
func (*DragRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{10}
}

func (x *DragRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *DragRequest) GetFromX() float64 {
	if x != nil {
		return x.FromX
	}
	return 0
}

func (x *DragRequest) GetFromY() float64 {
	if x != nil {
		return x.FromY
	}
	return 0
}

func (x *DragRequest) GetToX() float64 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *DragRequest) GetToY() float64 {
	if x != nil {
		return x.ToY
	}
	return 0
}

type PerformSecondaryActionRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	App          string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	ElementIndex string                 `protobuf:"bytes,2,opt,name=element_index,json=elementIndex,proto3" json:"element_index,omitempty"`
	// Action name from the accessibility tree's secondary actions list.
	Action        string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformSecondaryActionRequest) Reset() {
	*x = PerformSecondaryActionRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformSecondaryActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformSecondaryActionRequest) ProtoMessage() {}

func (x *PerformSecondaryActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformSecondaryActionRequest.ProtoReflect.Descriptor instead.
func (*PerformSecondaryActionRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{11}
}

func (x *PerformSecondaryActionRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *PerformSecondaryActionRequest) GetElementIndex() string {
	if x != nil {
		return x.ElementIndex
	}
	return ""
}

func (x *PerformSecondaryActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type SetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	ElementIndex  string                 `protobuf:"bytes,2,opt,name=element_index,json=elementIndex,proto3" json:"element_index,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{12}
}

func (x *SetValueRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *SetValueRequest) GetElementIndex() string {
	if x != nil {
		return x.ElementIndex
	}
	return ""
}

func (x *SetValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Generic response for action RPCs.
type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{13}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TurnEndedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional turn metadata.
	TurnId        string `protobuf:"bytes,1,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	ThreadId      string `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnEndedRequest) Reset() {
	*x = TurnEndedRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnEndedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnEndedRequest) ProtoMessage() {}

func (x *TurnEndedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnEndedRequest.ProtoReflect.Descriptor instead.
func (*TurnEndedRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{14}
}

func (x *TurnEndedRequest) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *TurnEndedRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type TurnEndedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnEndedResponse) Reset() {
	*x = TurnEndedResponse{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnEndedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnEndedResponse) ProtoMessage() {}

func (x *TurnEndedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnEndedResponse.ProtoReflect.Descriptor instead.
func (*TurnEndedResponse) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{15}
}

type CheckPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsRequest) Reset() {
	*x = CheckPermissionsRequest{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsRequest) ProtoMessage() {}

func (x *CheckPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{16}
}

type CheckPermissionsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AccessibilityGranted   bool                   `protobuf:"varint,1,opt,name=accessibility_granted,json=accessibilityGranted,proto3" json:"accessibility_granted,omitempty"`
	ScreenRecordingGranted bool                   `protobuf:"varint,2,opt,name=screen_recording_granted,json=screenRecordingGranted,proto3" json:"screen_recording_granted,omitempty"`
	// Deep link to open System Settings for the missing permission.
	AccessibilitySettingsUrl   string `protobuf:"bytes,3,opt,name=accessibility_settings_url,json=accessibilitySettingsUrl,proto3" json:"accessibility_settings_url,omitempty"`
	ScreenRecordingSettingsUrl string `protobuf:"bytes,4,opt,name=screen_recording_settings_url,json=screenRecordingSettingsUrl,proto3" json:"screen_recording_settings_url,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CheckPermissionsResponse) Reset() {
	*x = CheckPermissionsResponse{}
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsResponse) ProtoMessage() {}

func (x *CheckPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_computeruse_v1_computeruse_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_computeruse_v1_computeruse_proto_rawDescGZIP(), []int{17}
}

func (x *CheckPermissionsResponse) GetAccessibilityGranted() bool {
	if x != nil {
		return x.AccessibilityGranted
	}
	return false
}

func (x *CheckPermissionsResponse) GetScreenRecordingGranted() bool {
	if x != nil {
		return x.ScreenRecordingGranted
	}
	return false
}

func (x *CheckPermissionsResponse) GetAccessibilitySettingsUrl() string {
	if x != nil {
		return x.AccessibilitySettingsUrl
	}
	return ""
}

func (x *CheckPermissionsResponse) GetScreenRecordingSettingsUrl() string {
	if x != nil {
		return x.ScreenRecordingSettingsUrl
	}
	return ""
}

var File_computeruse_v1_computeruse_proto protoreflect.FileDescriptor

const file_computeruse_v1_computeruse_proto_rawDesc = "" +
	"\n" +
	" computeruse/v1/computeruse.proto\x12\x0ecomputeruse.v1\"\x11\n" +
	"\x0fListAppsRequest\"?\n" +
	"\x10ListAppsResponse\x12+\n" +
	"\x04apps\x18\x01 \x03(\v2\x17.computeruse.v1.AppInfoR\x04apps\"\x81\x01\n" +
	"\aAppInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleId\x12\x1d\n" +
	"\n" +
	"is_running\x18\x03 \x01(\bR\tisRunning\x12&\n" +
	"\x0fdays_since_used\x18\x04 \x01(\x05R\rdaysSinceUsed\"&\n" +
	"\x12GetAppStateRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\"\xda\x01\n" +
	"\x13GetAppStateResponse\x12-\n" +
	"\x12accessibility_tree\x18\x01 \x01(\tR\x11accessibilityTree\x12%\n" +
	"\x0escreenshot_png\x18\x02 \x01(\fR\rscreenshotPng\x122\n" +
	"\bapp_info\x18\x03 \x01(\v2\x17.computeruse.v1.AppInfoR\aappInfo\x129\n" +
	"\rwindow_bounds\x18\x04 \x01(\v2\x14.computeruse.v1.RectR\fwindowBounds\"P\n" +
	"\x04Rect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x01R\x06height\"\xc2\x01\n" +
	"\fClickRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12#\n" +
	"\relement_index\x18\x02 \x01(\tR\felementIndex\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\x12\x1f\n" +
	"\vclick_count\x18\x05 \x01(\x05R\n" +
	"clickCount\x12>\n" +
	"\fmouse_button\x18\x06 \x01(\x0e2\x1b.computeruse.v1.MouseButtonR\vmouseButton\"7\n" +
	"\x0fTypeTextRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"5\n" +
	"\x0fPressKeyRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x9b\x01\n" +
	"\rScrollRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12#\n" +
	"\relement_index\x18\x02 \x01(\tR\felementIndex\x12=\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x1f.computeruse.v1.ScrollDirectionR\tdirection\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x01R\x05pages\"s\n" +
	"\vDragRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x15\n" +
	"\x06from_x\x18\x02 \x01(\x01R\x05fromX\x12\x15\n" +
	"\x06from_y\x18\x03 \x01(\x01R\x05fromY\x12\x11\n" +
	"\x04to_x\x18\x04 \x01(\x01R\x03toX\x12\x11\n" +
	"\x04to_y\x18\x05 \x01(\x01R\x03toY\"n\n" +
	"\x1dPerformSecondaryActionRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12#\n" +
	"\relement_index\x18\x02 \x01(\tR\felementIndex\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"^\n" +
	"\x0fSetValueRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12#\n" +
	"\relement_index\x18\x02 \x01(\tR\felementIndex\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"@\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"H\n" +
	"\x10TurnEndedRequest\x12\x17\n" +
	"\aturn_id\x18\x01 \x01(\tR\x06turnId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"\x13\n" +
	"\x11TurnEndedResponse\"\x19\n" +
	"\x17CheckPermissionsRequest\"\x8a\x02\n" +
	"\x18CheckPermissionsResponse\x123\n" +
	"\x15accessibility_granted\x18\x01 \x01(\bR\x14accessibilityGranted\x128\n" +
	"\x18screen_recording_granted\x18\x02 \x01(\bR\x16screenRecordingGranted\x12<\n" +
	"\x1aaccessibility_settings_url\x18\x03 \x01(\tR\x18accessibilitySettingsUrl\x12A\n" +
	"\x1dscreen_recording_settings_url\x18\x04 \x01(\tR\x1ascreenRecordingSettingsUrl*s\n" +
	"\vMouseButton\x12\x1c\n" +
	"\x18MOUSE_BUTTON_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MOUSE_BUTTON_LEFT\x10\x01\x12\x16\n" +
	"\x12MOUSE_BUTTON_RIGHT\x10\x02\x12\x17\n" +
	"\x13MOUSE_BUTTON_MIDDLE\x10\x03*\x9e\x01\n" +
	"\x0fScrollDirection\x12 \n" +
	"\x1cSCROLL_DIRECTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SCROLL_DIRECTION_UP\x10\x01\x12\x19\n" +
	"\x15SCROLL_DIRECTION_DOWN\x10\x02\x12\x19\n" +
	"\x15SCROLL_DIRECTION_LEFT\x10\x03\x12\x1a\n" +
	"\x16SCROLL_DIRECTION_RIGHT\x10\x042\x99\a\n" +
	"\x12ComputerUseService\x12M\n" +
	"\bListApps\x12\x1f.computeruse.v1.ListAppsRequest\x1a .computeruse.v1.ListAppsResponse\x12V\n" +
	"\vGetAppState\x12\".computeruse.v1.GetAppStateRequest\x1a#.computeruse.v1.GetAppStateResponse\x12E\n" +
	"\x05Click\x12\x1c.computeruse.v1.ClickRequest\x1a\x1e.computeruse.v1.ActionResponse\x12K\n" +
	"\bTypeText\x12\x1f.computeruse.v1.TypeTextRequest\x1a\x1e.computeruse.v1.ActionResponse\x12K\n" +
	"\bPressKey\x12\x1f.computeruse.v1.PressKeyRequest\x1a\x1e.computeruse.v1.ActionResponse\x12G\n" +
	"\x06Scroll\x12\x1d.computeruse.v1.ScrollRequest\x1a\x1e.computeruse.v1.ActionResponse\x12C\n" +
	"\x04Drag\x12\x1b.computeruse.v1.DragRequest\x1a\x1e.computeruse.v1.ActionResponse\x12g\n" +
	"\x16PerformSecondaryAction\x12-.computeruse.v1.PerformSecondaryActionRequest\x1a\x1e.computeruse.v1.ActionResponse\x12K\n" +
	"\bSetValue\x12\x1f.computeruse.v1.SetValueRequest\x1a\x1e.computeruse.v1.ActionResponse\x12P\n" +
	"\tTurnEnded\x12 .computeruse.v1.TurnEndedRequest\x1a!.computeruse.v1.TurnEndedResponse\x12e\n" +
	"\x10CheckPermissions\x12'.computeruse.v1.CheckPermissionsRequest\x1a(.computeruse.v1.CheckPermissionsResponseBUZSgithub.com/tingly-dev/tingly-computer-use/go/pkg/proto/computeruse/v1;computerusev1b\x06proto3"

var (
	file_computeruse_v1_computeruse_proto_rawDescOnce sync.Once
	file_computeruse_v1_computeruse_proto_rawDescData []byte
)

func file_computeruse_v1_computeruse_proto_rawDescGZIP() []byte {
	file_computeruse_v1_computeruse_proto_rawDescOnce.Do(func() {
		file_computeruse_v1_computeruse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_computeruse_v1_computeruse_proto_rawDesc), len(file_computeruse_v1_computeruse_proto_rawDesc)))
	})
	return file_computeruse_v1_computeruse_proto_rawDescData
}

var file_computeruse_v1_computeruse_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_computeruse_v1_computeruse_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_computeruse_v1_computeruse_proto_goTypes = []any{
	(MouseButton)(0),                      // 0: computeruse.v1.MouseButton
	(ScrollDirection)(0),                  // 1: computeruse.v1.ScrollDirection
	(*ListAppsRequest)(nil),               // 2: computeruse.v1.ListAppsRequest
	(*ListAppsResponse)(nil),              // 3: computeruse.v1.ListAppsResponse
	(*AppInfo)(nil),                       // 4: computeruse.v1.AppInfo
	(*GetAppStateRequest)(nil),            // 5: computeruse.v1.GetAppStateRequest
	(*GetAppStateResponse)(nil),           // 6: computeruse.v1.GetAppStateResponse
	(*Rect)(nil),                          // 7: computeruse.v1.Rect
	(*ClickRequest)(nil),                  // 8: computeruse.v1.ClickRequest
	(*TypeTextRequest)(nil),               // 9: computeruse.v1.TypeTextRequest
	(*PressKeyRequest)(nil),               // 10: computeruse.v1.PressKeyRequest
	(*ScrollRequest)(nil),                 // 11: computeruse.v1.ScrollRequest
	(*DragRequest)(nil),                   // 12: computeruse.v1.DragRequest
	(*PerformSecondaryActionRequest)(nil), // 13: computeruse.v1.PerformSecondaryActionRequest
	(*SetValueRequest)(nil),               // 14: computeruse.v1.SetValueRequest
	(*ActionResponse)(nil),                // 15: computeruse.v1.ActionResponse
	(*TurnEndedRequest)(nil),              // 16: computeruse.v1.TurnEndedRequest
	(*TurnEndedResponse)(nil),             // 17: computeruse.v1.TurnEndedResponse
	(*CheckPermissionsRequest)(nil),       // 18: computeruse.v1.CheckPermissionsRequest
	(*CheckPermissionsResponse)(nil),      // 19: computeruse.v1.CheckPermissionsResponse
}
var file_computeruse_v1_computeruse_proto_depIdxs = []int32{
	4,  // 0: computeruse.v1.ListAppsResponse.apps:type_name -> computeruse.v1.AppInfo
	4,  // 1: computeruse.v1.GetAppStateResponse.app_info:type_name -> computeruse.v1.AppInfo
	7,  // 2: computeruse.v1.GetAppStateResponse.window_bounds:type_name -> computeruse.v1.Rect
	0,  // 3: computeruse.v1.ClickRequest.mouse_button:type_name -> computeruse.v1.MouseButton
	1,  // 4: computeruse.v1.ScrollRequest.direction:type_name -> computeruse.v1.ScrollDirection
	2,  // 5: computeruse.v1.ComputerUseService.ListApps:input_type -> computeruse.v1.ListAppsRequest
	5,  // 6: computeruse.v1.ComputerUseService.GetAppState:input_type -> computeruse.v1.GetAppStateRequest
	8,  // 7: computeruse.v1.ComputerUseService.Click:input_type -> computeruse.v1.ClickRequest
	9,  // 8: computeruse.v1.ComputerUseService.TypeText:input_type -> computeruse.v1.TypeTextRequest
	10, // 9: computeruse.v1.ComputerUseService.PressKey:input_type -> computeruse.v1.PressKeyRequest
	11, // 10: computeruse.v1.ComputerUseService.Scroll:input_type -> computeruse.v1.ScrollRequest
	12, // 11: computeruse.v1.ComputerUseService.Drag:input_type -> computeruse.v1.DragRequest
	13, // 12: computeruse.v1.ComputerUseService.PerformSecondaryAction:input_type -> computeruse.v1.PerformSecondaryActionRequest
	14, // 13: computeruse.v1.ComputerUseService.SetValue:input_type -> computeruse.v1.SetValueRequest
	16, // 14: computeruse.v1.ComputerUseService.TurnEnded:input_type -> computeruse.v1.TurnEndedRequest
	18, // 15: computeruse.v1.ComputerUseService.CheckPermissions:input_type -> computeruse.v1.CheckPermissionsRequest
	3,  // 16: computeruse.v1.ComputerUseService.ListApps:output_type -> computeruse.v1.ListAppsResponse
	6,  // 17: computeruse.v1.ComputerUseService.GetAppState:output_type -> computeruse.v1.GetAppStateResponse
	15, // 18: computeruse.v1.ComputerUseService.Click:output_type -> computeruse.v1.ActionResponse
	15, // 19: computeruse.v1.ComputerUseService.TypeText:output_type -> computeruse.v1.ActionResponse
	15, // 20: computeruse.v1.ComputerUseService.PressKey:output_type -> computeruse.v1.ActionResponse
	15, // 21: computeruse.v1.ComputerUseService.Scroll:output_type -> computeruse.v1.ActionResponse
	15, // 22: computeruse.v1.ComputerUseService.Drag:output_type -> computeruse.v1.ActionResponse
	15, // 23: computeruse.v1.ComputerUseService.PerformSecondaryAction:output_type -> computeruse.v1.ActionResponse
	15, // 24: computeruse.v1.ComputerUseService.SetValue:output_type -> computeruse.v1.ActionResponse
	17, // 25: computeruse.v1.ComputerUseService.TurnEnded:output_type -> computeruse.v1.TurnEndedResponse
	19, // 26: computeruse.v1.ComputerUseService.CheckPermissions:output_type -> computeruse.v1.CheckPermissionsResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_computeruse_v1_computeruse_proto_init() }
func file_computeruse_v1_computeruse_proto_init() {
	if File_computeruse_v1_computeruse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_computeruse_v1_computeruse_proto_rawDesc), len(file_computeruse_v1_computeruse_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_computeruse_v1_computeruse_proto_goTypes,
		DependencyIndexes: file_computeruse_v1_computeruse_proto_depIdxs,
		EnumInfos:         file_computeruse_v1_computeruse_proto_enumTypes,
		MessageInfos:      file_computeruse_v1_computeruse_proto_msgTypes,
	}.Build()
	File_computeruse_v1_computeruse_proto = out.File
	file_computeruse_v1_computeruse_proto_goTypes = nil
	file_computeruse_v1_computeruse_proto_depIdxs = nil
}
