// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: computeruse/v1/computeruse.proto

package computerusev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComputerUseService_ListApps_FullMethodName               = "/computeruse.v1.ComputerUseService/ListApps"
	ComputerUseService_GetAppState_FullMethodName            = "/computeruse.v1.ComputerUseService/GetAppState"
	ComputerUseService_Click_FullMethodName                  = "/computeruse.v1.ComputerUseService/Click"
	ComputerUseService_TypeText_FullMethodName               = "/computeruse.v1.ComputerUseService/TypeText"
	ComputerUseService_PressKey_FullMethodName               = "/computeruse.v1.ComputerUseService/PressKey"
	ComputerUseService_Scroll_FullMethodName                 = "/computeruse.v1.ComputerUseService/Scroll"
	ComputerUseService_Drag_FullMethodName                   = "/computeruse.v1.ComputerUseService/Drag"
	ComputerUseService_PerformSecondaryAction_FullMethodName = "/computeruse.v1.ComputerUseService/PerformSecondaryAction"
	ComputerUseService_SetValue_FullMethodName               = "/computeruse.v1.ComputerUseService/SetValue"
	ComputerUseService_TurnEnded_FullMethodName              = "/computeruse.v1.ComputerUseService/TurnEnded"
	ComputerUseService_CheckPermissions_FullMethodName       = "/computeruse.v1.ComputerUseService/CheckPermissions"
)

// ComputerUseServiceClient is the client API for ComputerUseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ComputerUseService provides Mac desktop GUI control capabilities.
// Transport: gRPC over Unix socket (local) or TCP (remote).
type ComputerUseServiceClient interface {
	// List running and recently used applications.
	ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error)
	// Get the accessibility tree and screenshot of an app's key window.
	// Must be called once per agent turn before interacting with the app.
	//
	// When `snapshot_only` is true, the call is strictly read-only:
	// the app is never launched, activated, or reopened, and a
	// NOT_FOUND error is returned if it is not currently running.
	GetAppState(ctx context.Context, in *GetAppStateRequest, opts ...grpc.CallOption) (*GetAppStateResponse, error)
	// Click an element by index or pixel coordinates from screenshot.
	Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Type literal text using keyboard input.
	TypeText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Press a key or key-combination (xdotool syntax).
	PressKey(ctx context.Context, in *PressKeyRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Scroll an element in a direction.
	Scroll(ctx context.Context, in *ScrollRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Drag from one point to another using pixel coordinates.
	Drag(ctx context.Context, in *DragRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Invoke a secondary accessibility action on an element.
	PerformSecondaryAction(ctx context.Context, in *PerformSecondaryActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Set the value of a settable accessibility element.
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Signal end of agent turn; clears visual cursor overlay state.
	TurnEnded(ctx context.Context, in *TurnEndedRequest, opts ...grpc.CallOption) (*TurnEndedResponse, error)
	// Check required macOS permissions (Accessibility + Screen Recording).
	CheckPermissions(ctx context.Context, in *CheckPermissionsRequest, opts ...grpc.CallOption) (*CheckPermissionsResponse, error)
}

type computerUseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComputerUseServiceClient(cc grpc.ClientConnInterface) ComputerUseServiceClient {
	return &computerUseServiceClient{cc}
}

func (c *computerUseServiceClient) ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppsResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_ListApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) GetAppState(ctx context.Context, in *GetAppStateRequest, opts ...grpc.CallOption) (*GetAppStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppStateResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_GetAppState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_Click_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) TypeText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_TypeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) PressKey(ctx context.Context, in *PressKeyRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_PressKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) Scroll(ctx context.Context, in *ScrollRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_Scroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) Drag(ctx context.Context, in *DragRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_Drag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) PerformSecondaryAction(ctx context.Context, in *PerformSecondaryActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_PerformSecondaryAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_SetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) TurnEnded(ctx context.Context, in *TurnEndedRequest, opts ...grpc.CallOption) (*TurnEndedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurnEndedResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_TurnEnded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerUseServiceClient) CheckPermissions(ctx context.Context, in *CheckPermissionsRequest, opts ...grpc.CallOption) (*CheckPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionsResponse)
	err := c.cc.Invoke(ctx, ComputerUseService_CheckPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputerUseServiceServer is the server API for ComputerUseService service.
// All implementations must embed UnimplementedComputerUseServiceServer
// for forward compatibility.
//
// ComputerUseService provides Mac desktop GUI control capabilities.
// Transport: gRPC over Unix socket (local) or TCP (remote).
type ComputerUseServiceServer interface {
	// List running and recently used applications.
	ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error)
	// Get the accessibility tree and screenshot of an app's key window.
	// Must be called once per agent turn before interacting with the app.
	//
	// When `snapshot_only` is true, the call is strictly read-only:
	// the app is never launched, activated, or reopened, and a
	// NOT_FOUND error is returned if it is not currently running.
	GetAppState(context.Context, *GetAppStateRequest) (*GetAppStateResponse, error)
	// Click an element by index or pixel coordinates from screenshot.
	Click(context.Context, *ClickRequest) (*ActionResponse, error)
	// Type literal text using keyboard input.
	TypeText(context.Context, *TypeTextRequest) (*ActionResponse, error)
	// Press a key or key-combination (xdotool syntax).
	PressKey(context.Context, *PressKeyRequest) (*ActionResponse, error)
	// Scroll an element in a direction.
	Scroll(context.Context, *ScrollRequest) (*ActionResponse, error)
	// Drag from one point to another using pixel coordinates.
	Drag(context.Context, *DragRequest) (*ActionResponse, error)
	// Invoke a secondary accessibility action on an element.
	PerformSecondaryAction(context.Context, *PerformSecondaryActionRequest) (*ActionResponse, error)
	// Set the value of a settable accessibility element.
	SetValue(context.Context, *SetValueRequest) (*ActionResponse, error)
	// Signal end of agent turn; clears visual cursor overlay state.
	TurnEnded(context.Context, *TurnEndedRequest) (*TurnEndedResponse, error)
	// Check required macOS permissions (Accessibility + Screen Recording).
	CheckPermissions(context.Context, *CheckPermissionsRequest) (*CheckPermissionsResponse, error)
	mustEmbedUnimplementedComputerUseServiceServer()
}

// UnimplementedComputerUseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputerUseServiceServer struct{}

func (UnimplementedComputerUseServiceServer) ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApps not implemented")
}
func (UnimplementedComputerUseServiceServer) GetAppState(context.Context, *GetAppStateRequest) (*GetAppStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppState not implemented")
}
func (UnimplementedComputerUseServiceServer) Click(context.Context, *ClickRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Click not implemented")
}
func (UnimplementedComputerUseServiceServer) TypeText(context.Context, *TypeTextRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TypeText not implemented")
}
func (UnimplementedComputerUseServiceServer) PressKey(context.Context, *PressKeyRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PressKey not implemented")
}
func (UnimplementedComputerUseServiceServer) Scroll(context.Context, *ScrollRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scroll not implemented")
}
func (UnimplementedComputerUseServiceServer) Drag(context.Context, *DragRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Drag not implemented")
}
func (UnimplementedComputerUseServiceServer) PerformSecondaryAction(context.Context, *PerformSecondaryActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PerformSecondaryAction not implemented")
}
func (UnimplementedComputerUseServiceServer) SetValue(context.Context, *SetValueRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedComputerUseServiceServer) TurnEnded(context.Context, *TurnEndedRequest) (*TurnEndedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TurnEnded not implemented")
}
func (UnimplementedComputerUseServiceServer) CheckPermissions(context.Context, *CheckPermissionsRequest) (*CheckPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPermissions not implemented")
}
func (UnimplementedComputerUseServiceServer) mustEmbedUnimplementedComputerUseServiceServer() {}
func (UnimplementedComputerUseServiceServer) testEmbeddedByValue()                            {}

// UnsafeComputerUseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputerUseServiceServer will
// result in compilation errors.
type UnsafeComputerUseServiceServer interface {
	mustEmbedUnimplementedComputerUseServiceServer()
}

func RegisterComputerUseServiceServer(s grpc.ServiceRegistrar, srv ComputerUseServiceServer) {
	// If the following call panics, it indicates UnimplementedComputerUseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComputerUseService_ServiceDesc, srv)
}

func _ComputerUseService_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_ListApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).ListApps(ctx, req.(*ListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_GetAppState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).GetAppState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_GetAppState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).GetAppState(ctx, req.(*GetAppStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_Click_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).Click(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_Click_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).Click(ctx, req.(*ClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_TypeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).TypeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_TypeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).TypeText(ctx, req.(*TypeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_PressKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PressKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).PressKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_PressKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).PressKey(ctx, req.(*PressKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_Scroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).Scroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_Scroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).Scroll(ctx, req.(*ScrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_Drag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DragRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).Drag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_Drag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).Drag(ctx, req.(*DragRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_PerformSecondaryAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerformSecondaryActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).PerformSecondaryAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_PerformSecondaryAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).PerformSecondaryAction(ctx, req.(*PerformSecondaryActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_TurnEnded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurnEndedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).TurnEnded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_TurnEnded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).TurnEnded(ctx, req.(*TurnEndedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerUseService_CheckPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerUseServiceServer).CheckPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputerUseService_CheckPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerUseServiceServer).CheckPermissions(ctx, req.(*CheckPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComputerUseService_ServiceDesc is the grpc.ServiceDesc for ComputerUseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputerUseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "computeruse.v1.ComputerUseService",
	HandlerType: (*ComputerUseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApps",
			Handler:    _ComputerUseService_ListApps_Handler,
		},
		{
			MethodName: "GetAppState",
			Handler:    _ComputerUseService_GetAppState_Handler,
		},
		{
			MethodName: "Click",
			Handler:    _ComputerUseService_Click_Handler,
		},
		{
			MethodName: "TypeText",
			Handler:    _ComputerUseService_TypeText_Handler,
		},
		{
			MethodName: "PressKey",
			Handler:    _ComputerUseService_PressKey_Handler,
		},
		{
			MethodName: "Scroll",
			Handler:    _ComputerUseService_Scroll_Handler,
		},
		{
			MethodName: "Drag",
			Handler:    _ComputerUseService_Drag_Handler,
		},
		{
			MethodName: "PerformSecondaryAction",
			Handler:    _ComputerUseService_PerformSecondaryAction_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _ComputerUseService_SetValue_Handler,
		},
		{
			MethodName: "TurnEnded",
			Handler:    _ComputerUseService_TurnEnded_Handler,
		},
		{
			MethodName: "CheckPermissions",
			Handler:    _ComputerUseService_CheckPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "computeruse/v1/computeruse.proto",
}
